### PR TITLE
Use uptimeMonth for the default value of uptime

### PR DESCRIPTION
**Pull request by unixfox**
See https://github.com/searxng/searx-space/pull/124#discussion_r985884249

### CODE REVIEW

**Comment by dalf** [comment]
The line to change is in main.js:
https://github.com/searxng/searx-space/blob/60dd774d0ec5b7ffe831c32f601df96986a9f1ee/html/main.js#L863

`this.value.uptimeWeek` --> `uptimeMonth`.

The data comes from https://raw.githubusercontent.com/searxng/searx-instances-uptime/master/history/summary.json

in following sample, the `uptime` field is ignored by the code:
```
  {
    "name": "searx.space",
    "url": "https://searx.space",
    "icon": "https://icons.duckduckgo.com/ip3/searx.space.ico",
    "slug": "searx-space",
    "status": "up",
    "uptime": "100.00%",
    "uptimeDay": "100.00%",
    "uptimeWeek": "100.00%",
    "uptimeMonth": "100.00%",
    "uptimeYear": "100.00%",
    "time": 686,
    "timeDay": 613,
    "timeWeek": 632,
    "timeMonth": 649,
    "timeYear": 686,
    "dailyMinutesDown": {}
  },
```

**Comment by unixfox** [comment]
fixed

**Comment by unixfox** [comment]
@dalf can I merge?

**Comment by dalf** [comment]
Merged (in my previous comment, I forgot line 860)

**Pull request merged**
