### PR TITLE
[mod] Add notice that SearX instances will get removed

### LINKED ISSUE #141: Add notice that SearX instances will get removed
We should add a notice on the very top liking to this GitHub discussion: https://github.com/searxng/searx-instances/discussions/336

Something like this but bigger: 
image

```
SearX instances (not SearXNG) will soon get removed from this list, [see here](https://github.com/searxng/searx-instances/discussions/336).
```

@dalf in case you may have some free time, feel free to submit a PR :).

### PR DESCRIPTION
**Pull request by return42**
Closes: https://github.com/searxng/searx-space/issues/141

### CODE REVIEW

**Comment by unixfox** [comment]
Do you have a screenshot of the rendering of that new page with the announcement text?

**Comment by return42** [comment]
Here is a screenshot of the HTML page (without the instance list) .. the "announcement" is a part of the header and is shown in all tabs

grafik

Here is a screenshot of the "About" tab.

grafik

**Comment by unixfox** [comment]
Thank you, do you know if that is shown properly when viewing the page on a smartphone/mobile phone?

**Comment by return42** [comment]
I think so ...

grafik

**Review by unixfox — APPROVED** [review]
Good for merging. Who got access to rebuild the container on the VPS though?

**Comment by return42** [comment]
> Who got access to rebuild the container on the VPS though?

IDK but its already updated  .. https://searx.space/#  .. clean browser's cache to get modified CSS.

**Pull request merged**
