### PR TITLE
Add http2 support

### PR DESCRIPTION
**Pull request by ononoki1**

### CODE REVIEW

**Comment by ononoki1** [comment]
This pr adds support for http2 when checking instances and fixes some minor issues in README.md. This is done by updating httpx module from 0.11.0 to 0.14.0 and tweaking some usage. The updated version was already tested successfully on my Debian bullseye server.

**Comment by unixfox** [comment]
This only tries HTTP2 and that's it? Or it does try HTTP1 if HTTP2 fails?

By the way please squash all your commits and give them a real name.

**Comment by ononoki1** [comment]
It will use http2 when possible. Otherwise http1 will be used.

I plan to go to bed now (it's UTC+8 here), so I may rebase it several hours later.

**Comment by ononoki1** [comment]
> By the way please squash all your commits and give them a real name.

Done.

**Comment by dalf** [comment]
Why not use the last version of httpx?

Here a patch
Notes:
* I have not check Tor, but the mode parameter ( `mode="TUNNEL_ONLY"` )  is removed but AFIR  the default options are the good one.
* `follow_redirects=True` is required because httpx don't follow redirect now.

```diff
diff --git a/requirements.txt b/requirements.txt
index a6ac8be..056457d 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -1,5 +1,5 @@
 pyOpenSSL==21.0.0
-httpx[http2]==0.14.0
+httpx[http2]==0.22.0
 brotlipy==0.7.0
 uvloop==0.14.0
 dnspython==1.16.0
diff --git a/searxstats/common/http.py b/searxstats/common/http.py
index 648cab5..ee42574 100644
--- a/searxstats/common/http.py
+++ b/searxstats/common/http.py
@@ -1,6 +1,7 @@
 import sys
 import ssl
 import asyncio
+import logging
 from urllib.parse import urlparse
 from enum import Enum
 
@@ -24,10 +25,7 @@ class NetworkType(Enum):
 
 
 NETWORK_PROXIES = {
-    NetworkType.TOR: httpx.Proxy(
-        url=TOR_HTTP_PROXY,
-        mode="TUNNEL_ONLY"  # Tor is a tunnel only proxy
-    )
+    NetworkType.TOR: httpx.Proxy(url=TOR_HTTP_PROXY)
 }
 
 TOR_PROXY_ERROR = {
@@ -63,7 +61,7 @@ async def new_client(*args, **kwargs):
             network_type = kwargs['network_type']
             kwargs['proxies'] = NETWORK_PROXIES.get(network_type, None)
         del kwargs['network_type']
-    async with httpx.AsyncClient(*args, **kwargs, verify=SSL_CONTEXT, http2=True) as session:
+    async with httpx.AsyncClient(*args, **kwargs, verify=SSL_CONTEXT, http2=True, follow_redirects=True) as session:
         session._network_type = network_type  # pylint: disable=protected-access
         yield session
 
@@ -155,3 +153,5 @@ async def initialize(loop=None):
     """
     global request
     request = UseQueue(worker_count=1, loop=loop)(request)
+    for logger_name in ('hpack.hpack', 'hpack.table', 'httpx._client'):
+        logging.getLogger(logger_name).setLevel(logging.WARNING)
```

---

https://github.com/searxng/searx-space/blob/4fe07c442f143963e5cbd2ea46b0405b6e6eb808/searxstats/common/http.py#L158-L159

For information, these two lines makes sure only one HTTP request runs at a time. It avoids bugs in httpx version 0.11.0

I think it can be removed now.

**Comment by ononoki1** [comment]
I just tested and found that `mode="TUNNEL_ONLY"` is necessary. Otherwise http error 405 would occur.

So, I decided to still use httpx 0.14.0 and keep other parts of your patch. @dalf

**Comment by dalf** [comment]
The last version of httpx works with Tor using SOCKS:

<details>
<summary>patch to use httpx 0.22, works with Tor</summary>

```diff
diff --git a/requirements.txt b/requirements.txt
index a6ac8be..755f830 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -1,5 +1,5 @@
 pyOpenSSL==21.0.0
-httpx[http2]==0.14.0
+httpx[http2,socks]==0.22.0
 brotlipy==0.7.0
 uvloop==0.14.0
 dnspython==1.16.0
diff --git a/searxstats/common/http.py b/searxstats/common/http.py
index 648cab5..75614c7 100644
--- a/searxstats/common/http.py
+++ b/searxstats/common/http.py
@@ -1,6 +1,7 @@
 import sys
 import ssl
 import asyncio
+import logging
 from urllib.parse import urlparse
 from enum import Enum
 
@@ -10,7 +11,7 @@ from .utils import exception_to_str
 from .queuecalls import UseQueue
 from .memoize import Memoize
 from .ssl_info import SSL_CONTEXT
-from ..config import TOR_HTTP_PROXY
+from ..config import TOR_SOCKS_PROXY_HOST, TOR_SOCKS_PROXY_PORT
 
 if not sys.version_info.major == 3 and sys.version_info.minor >= 7:
     from contextlib import asynccontextmanager  # pylint: disable=no-name-in-module
@@ -24,10 +25,7 @@ class NetworkType(Enum):
 
 
 NETWORK_PROXIES = {
-    NetworkType.TOR: httpx.Proxy(
-        url=TOR_HTTP_PROXY,
-        mode="TUNNEL_ONLY"  # Tor is a tunnel only proxy
-    )
+    NetworkType.TOR: httpx.Proxy(url=f'socks5://{TOR_SOCKS_PROXY_HOST}:{TOR_SOCKS_PROXY_PORT}')
 }
 
 TOR_PROXY_ERROR = {
@@ -63,7 +61,7 @@ async def new_client(*args, **kwargs):
             network_type = kwargs['network_type']
             kwargs['proxies'] = NETWORK_PROXIES.get(network_type, None)
         del kwargs['network_type']
-    async with httpx.AsyncClient(*args, **kwargs, verify=SSL_CONTEXT, http2=True) as session:
+    async with httpx.AsyncClient(*args, **kwargs, verify=SSL_CONTEXT, http2=True, follow_redirects=True) as session:
         session._network_type = network_type  # pylint: disable=protected-access
         yield session
 
@@ -113,6 +111,7 @@ async def request(method, *args, **kwargs):
         else:  # socket.gaierror, ssl.SSLError, h11._util.RemoteProtocolError
             error = exception_to_str(wrapped_ex)
     except httpx.ProxyError as ex:
+        print(ex)
         error = exception_to_str(ex)
         session = getattr(method, '__self__', None)
         network_type = NetworkType.NORMAL
@@ -155,3 +154,5 @@ async def initialize(loop=None):
     """
     global request
     request = UseQueue(worker_count=1, loop=loop)(request)
+    for logger_name in ('hpack.hpack', 'hpack.table', 'httpx._client'):
+        logging.getLogger(logger_name).setLevel(logging.WARNING)
diff --git a/searxstats/config.py b/searxstats/config.py
index bc4afd5..c12cc54 100644
--- a/searxstats/config.py
+++ b/searxstats/config.py
@@ -2,7 +2,6 @@ import os
 import hashlib
 
 # Tor
-TOR_HTTP_PROXY = "http://127.0.0.1:9051"
 TOR_SOCKS_PROXY_HOST = "127.0.0.1"
 TOR_SOCKS_PROXY_PORT = 9050
```

</details>

**Comment by dalf** [comment]
Thank you @ononoki1 for this PR !

**Pull request merged**
